# Generated by Django 5.1.3 on 2024-11-13 04:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('duration_hours', models.PositiveIntegerField()),
                ('track_name', models.CharField(max_length=200)),
                ('avg_lap_time_seconds', models.PositiveIntegerField(help_text='Average lap time in seconds')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_races', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RaceDriver',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timezone', models.CharField(help_text="Driver's timezone (e.g., 'America/New_York')", max_length=50)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='races.race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('race', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DrivingAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('race_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_assignments', to='races.racedriver')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityWindow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('race_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='races.racedriver')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
