[tool.black]
line-length = 120

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
filter_files = true

[tool.poetry]
name = "stintmanager"
version = "0.1.0"
description = ""
authors = ["Francis Genet <francis.genet@gmail.com>"]

[tool.poetry.dependencies]
python = "3.11.7"
Django = "5.0.2"
djangorestframework = "3.14.0"
djangorestframework-simplejwt = "5.3.1"
psycopg = "3.1.18"
django-cors-headers = "^4.3.1"

[tool.poetry.dev-dependencies]
django-extensions = "^3.2.0"
ipdb = "^0.13.9"
flake8 = "^4.0.1"
black = "^22.6.0"
isort = "^5.10.1"

[tool.poetry.group.dev.dependencies]
werkzeug = "^3.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
