# Generated by Django 4.0.6 on 2022-08-06 05:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('games', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), choices=[('iRacing', 'Iracing')], size=None)),
                ('paint_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_name'),
        ),
    ]
