# Generated by Django 4.0.6 on 2022-08-06 05:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('track', models.CharField(max_length=255)),
                ('game', models.CharField(choices=[('iRacing', 'Iracing')], default='iRacing', max_length=255)),
                ('car', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('paint_scheme', models.URLField(blank=True, null=True)),
                ('setup_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
