# Generated by Django 4.2.10 on 2024-03-02 22:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("driver", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=1000)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PitStop",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.TextField(choices=[("short", "Short"), ("long", "Long")])),
                ("driver", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="driver.driver")),
                ("race", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="race.race")),
            ],
        ),
        migrations.CreateModel(
            name="AverageLapTime",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("average_lap_time", models.DurationField()),
                ("driver", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="driver.driver")),
                ("race", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="race.race")),
            ],
        ),
        migrations.AddConstraint(
            model_name="pitstop",
            constraint=models.UniqueConstraint(fields=("driver", "race"), name="uniquetogether_pitstop_driver_race"),
        ),
        migrations.AddConstraint(
            model_name="averagelaptime",
            constraint=models.UniqueConstraint(
                fields=("driver", "race"), name="uniquetogether_avg_laptime_driver_race"
            ),
        ),
    ]
